image: sakshamsharma/docker-hakyll:v2

pages:
  script:
    - stack build
    - stack exec site build
  after_script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
