image: haskell:latest

pages:
  cache:
    paths:
      - _cache
      - .stack
      - $HOME/.stack
  before_script:
    - apt-get update
    - bash -c "yes | apt-get install git"
    - stack setup
    - stack build
  script:
    - stack exec site build
  after_script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
