image: haskell:8.0.1

variables:
  STACK_ROOT: "${CI_PROJECT_DIR}/.stack"

pages:
  cache:
    key: ${CI_BUILD_REF_NAME}
    paths:
      - .stack
      - .stack-work
  before_script:
    - apt-get update
    - bash -c "yes | apt-get install git"
    - stack install --only-dependencies --install-ghc
    - stack build
  script:
    - stack exec site clean
    - stack exec site build
  after_script:
    - mv _site public
  artifacts:
    paths:
      - public
  only:
    - master
