image: haskell:7.10.3

pages:
  cache:
    paths:
      - _cache
      - .stack
  before_script:
    - apt-get update
    - bash -c "yes | apt-get install git"
    - export STACK_ROOT=`pwd`/.stack
    - stack install --only-dependencies
    - stack setup
    - stack build
  script:
    - stack exec site build
  artifacts:
    paths:
      - _site
  only:
    - master
