language: haskell
branches:
  only:
    - master
cache:
  directories:
  - $HOME/.stack
  - .stack-work
before_install:
  - echo "override before_install"
install:
  - wget https://github.com/commercialhaskell/stack/releases/download/v1.6.5/stack-1.6.5-linux-x86_64-static.tar.gz -O stack.gz
  - tar xvf stack.gz
  - chmod +x stack-1.6.5-linux-x86_64-static/stack
  - stack-1.6.5-linux-x86_64-static/stack setup
  - stack-1.6.5-linux-x86_64-static/stack build
before_script:
  - echo "override before_script"
script:
  - bash ./build.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL="saksham0808@gmail.com"
  - ENCRYPTION_LABEL="e81a3a1fc839"
