language: haskell
branches:
  only:
    - master 
cache:
  directories:
  - $HOME/.stack
before_install:
  - echo "override before_install"
install:
  - wget https://github.com/commercialhaskell/stack/releases/download/v1.0.0/stack-1.0.0-linux-x86_64.tar.gz -O stack.gz
  - tar xvf stack.gz
  - chmod +x stack-1.0.0-linux-x86_64/stack
  - stack-1.0.0-linux-x86_64/stack setup
  - stack-1.0.0-linux-x86_64/stack build
before_script:
  - echo "override before_script"
script:
  - bash ./build.sh
env:
  global:
  - COMMIT_AUTHOR_EMAIL="saksham0808@gmail.com"
  - ENCRYPTED_LABEL="e81a3a1fc839"
