resolver: lts-11.1

packages:
- '.'

# Override default flag values for local packages and extra-deps
flags: {}

extra-deps:
- hakyll-4.12.0.1

# Extra package databases containing global packages
extra-package-dbs: []
